name= input("enter your name")
branch= input("tell me your branch")
gender= input("what is your gender")
collegeName= input("what is your college name")
Age= int(input("enter your age"))
print("name: ",name)
print("branch: ",branch)
print("gender: ", gender)
print("collegeName: ", collegeName)
print("Age: ", Age)
